server:
  port: 10001

processor:
  kafkaProps:
    HelloWorldProcessor:
      bootStrap: 11
      topic: 11
      keySerializer: org.apache.kafka.common.serialization.LongSerializer
      groupId: 11
      offset: LATEST
      poll: 11
      actor: io.penguin.consumer.serializer.NoOpActor
      concurrency: 11
      redisProps:
        expireTime: 11
        redisHosts: 11