spring:
  mvc:
    async:
      request-timeout: 5s
penguin:
  version: v1
  metadata:
    name: FirstExample
  spec:
    resources:
      - name: CASSANDRA
        spec:
          keySpace: local
          hosts: 127.0.0.1
      - name: LETTUCE_CACHE
        spec:
          expireMilliseconds: 100
          redisUris: 127.0.0.1
      - name: OVER_WRITER
    workers:
      - name: BookStore
        kind: BASE
        aggregatedTarget: io.penguin.penguincore.reader.BookStoreReader
        containers:
          - name: BookStore_source
            kind: CASSANDRA
            spec:
              valueType: io.penguin.penguincore.model.CBookStore
          - name: BookStore_cache
            kind: LETTUCE_CACHE
            spec:
              prefix: bs
              downStreamName: BookStore_source
              codecConfig:
                codec: io.penguin.penguincodec.JsonCodec
                target: io.penguin.penguincore.model.CBookStore
                compress: GZIP
          - name: BookOverWriter
            kind: OVER_WRITER
            spec:
              - io.penguin.penguincore.overwrite.Value2OverWriter

      - name: Book
        kind: BASE
        aggregatedTarget: io.penguin.penguincore.reader.BookReader
        containers:
          - name: Book_sourceV2
            kind: Bean
            spec:
              name: bookStoreBeanReader
              domainClass: io.penguin.penguincore.model.CBookStore
              idClass: java.lang.Long
          - name: Book_cache
            kind: LETTUCE_CACHE
            spec:
              prefix: p
              downStreamName: Book_sourceV2
              codecConfig:
                codec: io.penguin.penguincodec.JsonCodec
                target: io.penguin.penguincore.model.CBook
                compress: GZIP
