penguin:
  version: v1
  metadata:
    name: FirstExample
  spec:
    workers:
      - name: myFirst
        kind: BASE
        aggregatedTarget: io.penguin.penguincore.reader.FirstExample
        containers:
        - name: source
          kind: CASSANDRA
          spec:
            idColumn: id
            keySpace: local
            hosts: 127.0.0.1
            columns: first, id
            table: first_table
            valueType: io.penguin.penguincore.model.MyModel

        - name: First
          kind: LETTUCE_CACHE
          spec:
            expireMilliseconds: 100
            prefix: p
            downStreamName: source
            codecConfig:
              codec: io.penguin.penguincodec.JsonCodec
              target: io.penguin.penguincore.model.MyModel
            redisUris: 127.0.0.1

        - name: OverWrite
          kind: OVER_WRITER
          spec:
            first: io.penguin.penguincore.overwrite.ValueOverWriter
            second: io.penguin.penguincore.overwrite.Value2OverWriter