penguin:
  version: v1
  kind: penguin

  metadata:
    name: my-first

  spec:
    containers:
      - name: static
        kind: lettuce
        spec:
          expireMilliseconds: 100
          prefix: p
          redisUris:
            - 127.0.0.1
            - 127.0.0.1
          downStreamName: none
          codecConfig:
            codec: io.penguin.penguincodec.JsonCodec
