penguin:
  version: v1
  metadata:
    name: FirstExample
  spec:
    workers:
      - name: myFirst
        kind: BASE
        aggregatedTarget: io.penguin.penguincore.reader.FirstExample
        containers:
        - name: source
          kind: CASSANDRA
          spec:
            idColumn: id
            keySpace: local
            hosts: 127.0.0.1
            columns: first
            table: first
            valueType: java.lang.Long

        - name: First
          kind: LETTUCE_CACHE
          spec:
            expireMilliseconds: 100
            prefix: p
            downStreamName: static
            codecConfig:
              codec: io.penguin.penguincodec.JsonCodec
            redisUris: 127.0.0.1
