penguin:
  version: v1
  kind: BASE

  metadata:
    name: FirstExample
  spec:
    workers:
      name: myFirst
      aggregatedTarget: io.penguin.penguincore.reader.FirstExample
      containers:
      - name: static
        kind: hello
      - name: First
        kind: remote_cache
        spec:
          expireMilliseconds: 100
          prefix: p
          downStreamName: static
          codecConfig:
            codec: io.penguin.penguincodec.JsonCodec
          redisUris: 127.0.0.1